menu:
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Resources', url: '/resources'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/rgriva'}
- {icon: 'twitter', link: 'https://twitter.com/raulguarini'}
- {icon: 'instagram', link: 'https://instagram.com/raulguarini'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/rgriva'}

contacts:
- {name: 'Raul Guarini Riva', 
   title: 'Assistant Professor', 
   department: 'EPGE - Brazilian School of Economics and Finance', 
   institution: 'Fundação Getulio Vargas', 
   institution_address: 'Praia de Botafogo, 190 - Rio de Janeiro', 
   phone: '21 97016 1771', 
   email: 'raul.riva at fgv.br', 
   office: '1121B', 
   image: 'assets/img/Urca_2025.jpg'}
